# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisServerLite < Formula
  desc "A lightweight Redis server implementation in Go."
  homepage "https://github.com/OmkarPh/redis-server-lite"
  version "0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/OmkarPh/redis-server-lite/releases/download/v0.1/redis-server-lite_0.1_darwin_arm64.tar.gz"
      sha256 "05d009eb0fb424532740054a1732d43dfe9bf8bc5ce7ee67f9e6168888c5a696"

      def install
        bin.install "redis-server-lite"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/OmkarPh/redis-server-lite/releases/download/v0.1/redis-server-lite_0.1_darwin_amd64.tar.gz"
      sha256 "90cd4f2163d91f9d35d230baa875338d020b17f861f6c63efe504b50ffadd1f3"

      def install
        bin.install "redis-server-lite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OmkarPh/redis-server-lite/releases/download/v0.1/redis-server-lite_0.1_linux_arm64.tar.gz"
      sha256 "518920ab520434e3ee5ef8595126e6e4849fa0fb3d8a887428b222fdd733801e"

      def install
        bin.install "redis-server-lite"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/OmkarPh/redis-server-lite/releases/download/v0.1/redis-server-lite_0.1_linux_amd64.tar.gz"
      sha256 "f6d39173d17848c4614573094e19fe1698f73cbadbf83428dffcbecdcde9ef04"

      def install
        bin.install "redis-server-lite"
      end
    end
  end

  test do
    assert_match /A simple port-forward wrapper tool for multiple pods\/deployments\/services/, shell_output("#{bin}/kubepfm -h", 0)
  end
end
