# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisServerLite < Formula
  desc "A lightweight Redis server implementation in Go."
  homepage "https://github.com/OmkarPh/redis-server-lite"
  version "0.0.1-test-actions-10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/OmkarPh/test-redis-server-lite/releases/download/v0.0.1-test-actions-10/redis-server-lite_0.0.1-test-actions-10_darwin_arm64.tar.gz"
      sha256 "4c774873772416b60dbf3cac7d6f2bcb05b4d79a8de9d0225eee63bc6c6f7188"

      def install
        bin.install "redis-server-lite"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/OmkarPh/test-redis-server-lite/releases/download/v0.0.1-test-actions-10/redis-server-lite_0.0.1-test-actions-10_darwin_amd64.tar.gz"
      sha256 "72e8bd2cf0528029891ad141e274b515d37f3c662a88a1f9dda7a086adeff61d"

      def install
        bin.install "redis-server-lite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OmkarPh/test-redis-server-lite/releases/download/v0.0.1-test-actions-10/redis-server-lite_0.0.1-test-actions-10_linux_arm64.tar.gz"
      sha256 "71445b58578222bf226415249e937472bef32400707966359f99e66bc76ed5b7"

      def install
        bin.install "redis-server-lite"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/OmkarPh/test-redis-server-lite/releases/download/v0.0.1-test-actions-10/redis-server-lite_0.0.1-test-actions-10_linux_amd64.tar.gz"
      sha256 "571207d03bd3852b33e7bb71e0a8b1fa84d5e785b06362ae032677c1aa6d7d36"

      def install
        bin.install "redis-server-lite"
      end
    end
  end

  test do
    assert_match /A simple port-forward wrapper tool for multiple pods\/deployments\/services/, shell_output("#{bin}/kubepfm -h", 0)
  end
end
